# Generated by Django 4.2.4 on 2023-10-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0003_alter_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
