# Generated by Django 4.2.4 on 2023-10-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0007_device_brand_device_device_type_device_starting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='images',
            field=models.ImageField(default='', upload_to='device/image'),
        ),
    ]
