# Generated by Django 4.2.4 on 2023-10-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0008_device_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='images',
            field=models.FileField(default='', upload_to='device/image'),
        ),
    ]
